#*****************************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# project_1.tcl: Tcl script for re-creating project 'project_1'
#
# Generated by Vivado on Tue Aug 06 10:57:25 +0800 2024
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (project_1.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    <none>
#
# 3. The following remote source files that were added to the original project:-
#
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/master_wr_fifo/master_wr_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/hmc7044_cfg_rom/hmc7044_cfg_rom.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/encode_align_fifo/encode_align_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/encode_x_align_fifo/encode_x_align_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/cache_rd_fifo/cache_rd_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/FBC_vin_buffer_fifo/FBC_vin_buffer_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/fbc_cache_fifo/fbc_cache_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/cache_bit_ram/cache_bit_ram.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/msg_comm_rx_ram/msg_comm_rx_ram.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/msg_comm_tx_fifo/msg_comm_tx_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/pll_2/pll_2.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/pll/pll.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/CRC32_D8.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/FBC_cache.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/FBC_vin_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/FBC_vout_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/motor/PID_control_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/acc_ctrl_rx_drv.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/acc_demo_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/acc_demo_flag_trim.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/acc_time_ctrl_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ad5445_config.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ad5592_config.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ad5592_spi_if.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ad7680_spi_if.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/align_unit.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/arbitrate_bpsi.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_clock_module.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/aurora_64b66b_0_exdes.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_gt_common_wrapper.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_support.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_support_reset_logic.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_clock_module.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/aurora_64b66b_1_exdes.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_support.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_support_reset_logic.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/aurora_64b/aurora_64b66b_tx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/bpsi_top_if_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/motor/bspi_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/command_map.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/ddr_top.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds_frame_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds/eds_top_if.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/encode_align.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/encode_align_unit.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/encode_continuity_check.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/encode_process.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/encode_process_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/encode_tx_drv.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/fast_shutter_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/motor/fbc_sensor_process.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/fpga_heart_beat.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/base/handshake.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/hmc7044_config.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/hmc7044_spi_if.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds/image_rx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds/iser2des_1_to_12.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/laser_aom_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/laser_comm_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds/lval_synncode_0chan.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds/lval_synncode_Nchan.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/max5216_spi_if.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/mem_burst_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/mem_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/mem_read_arbi.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/mem_vin_buffer_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/mem_vout_buffer_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/mem_write_arbi.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/motion_top_if.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/pmt_master_sel.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/reg_delay.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/reset_generate.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/scan_cmd_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/scan_flag_generate.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/scan_state_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/serial_master_drv.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/serial_rx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/serial_rx_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/serial_tx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/serial_tx_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/msg_comm/slave_comm.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/msg_comm/slave_comm_rx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/msg_comm/slave_comm_x4_tx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds/train_word_align.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/eds/training.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/motor/trigger_generate.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/uart/uart.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/uart/uart_rx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/uart/uart_tx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/w_encoder_process_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/base/widen_enable.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/x_encoder_process.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/base/xpm_async_fifo.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/base/xpm_sync_fifo.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/mfpga_top.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/coe/hmc7044_cfg.coe"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/ddr3_mig/mig_a.prj"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/msg_comm/slave_comm_tx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/test_sim_fifo/test_sim_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/test_encode_fifo/test_encode_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/test_data_to_ddr3_fifo/test_data_to_ddr3_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/fbc_voltage_fifo/fbc_voltage_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/bpsi_fbc_fifo/bpsi_fbc_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/bps_divider/bps_divider.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/spi_slave_ack_fifo/spi_slave_ack_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/laser_rx_fifo/laser_rx_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/ddr3_mig/ddr3_mig.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/FBC_vout_buffer_fifo/FBC_vout_buffer_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/laser_uart_fifo/laser_uart_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/aurora_64b66b_1/aurora_64b66b_1.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/eds_to_aurora_fifo/eds_to_aurora_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/sync_eds_encode_fifo/sync_eds_encode_fifo.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/rx_dist_mem/rx_dist_mem.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/ip/acc_demo_encode_mem/acc_demo_encode_mem.xci"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/constrs_1/new/debug.xdc"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/constrs_1/new/timing.xdc"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/constrs_1/new/mfpga_io_v2.xdc"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/ddr_sim/wiredly.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/ddr_sim/ddr3_model.sv"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/ddr/tb_ddr_top.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/tb_acc_demo_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/tb_laser_aom_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/tb_FBC_cache.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/tb_acc_demo_flag_trim.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/tb_fast_shutter_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/overload/aom_trig_overload.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/testbench/message_comm_tx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/testbench/tb_encode_align.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/testbench/pcie_sim/pcie_aurora_64b66b_rx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/testbench/tb_bpsi_top_if_v2.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/testbench/tb_slave_comm.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/testbench/tb_encode_process.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/testbench/tb_laser_comm_ctrl.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/sim_acc_demo_flag_rx_drv.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/acc_demo_flag_tx_drv.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/msg_comm/message_comm_rx.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/spi/tb_spi_master.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/serial_slave_drv.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/serial/encode_rx_drv.v"
#    "D:/workspace/pcg-prj/pcg-timing-prj/project_src/sources_1/new/spi/spi_reg_map.v"
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/project_src/sources_1/ip/master_wr_fifo/master_wr_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/hmc7044_cfg_rom/hmc7044_cfg_rom.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/encode_align_fifo/encode_align_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/encode_x_align_fifo/encode_x_align_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/cache_rd_fifo/cache_rd_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/FBC_vin_buffer_fifo/FBC_vin_buffer_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/fbc_cache_fifo/fbc_cache_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/cache_bit_ram/cache_bit_ram.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/msg_comm_rx_ram/msg_comm_rx_ram.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/msg_comm_tx_fifo/msg_comm_tx_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/pll_2/pll_2.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/pll/pll.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/CRC32_D8.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/FBC_cache.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/FBC_vin_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/FBC_vout_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/motor/PID_control_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/acc_ctrl_rx_drv.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/acc_demo_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/acc_demo_flag_trim.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/acc_time_ctrl_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ad5445_config.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ad5592_config.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ad5592_spi_if.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ad7680_spi_if.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/align_unit.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/arbitrate_bpsi.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_clock_module.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/aurora_64b66b_0_exdes.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_gt_common_wrapper.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_support.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_support_reset_logic.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_clock_module.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/aurora_64b66b_1_exdes.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_support.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_support_reset_logic.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/aurora_64b/aurora_64b66b_tx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/bpsi_top_if_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/motor/bspi_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/command_map.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/ddr_top.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds_frame_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds/eds_top_if.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/encode_align.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/encode_align_unit.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/encode_continuity_check.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/encode_process.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/encode_process_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/encode_tx_drv.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/fast_shutter_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/motor/fbc_sensor_process.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/fpga_heart_beat.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/base/handshake.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/hmc7044_config.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/hmc7044_spi_if.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds/image_rx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds/iser2des_1_to_12.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/laser_aom_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/laser_comm_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds/lval_synncode_0chan.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds/lval_synncode_Nchan.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/max5216_spi_if.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/mem_burst_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/mem_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/mem_read_arbi.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/mem_vin_buffer_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/mem_vout_buffer_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/mem_write_arbi.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/motion_top_if.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/pmt_master_sel.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/reg_delay.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/reset_generate.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/scan_cmd_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/scan_flag_generate.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/scan_state_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/serial_master_drv.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/serial_rx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/serial_rx_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/serial_tx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/serial_tx_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/msg_comm/slave_comm.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/msg_comm/slave_comm_rx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/msg_comm/slave_comm_x4_tx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds/train_word_align.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/eds/training.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/motor/trigger_generate.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/uart/uart.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/uart/uart_rx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/uart/uart_tx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/w_encoder_process_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/base/widen_enable.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/x_encoder_process.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/base/xpm_async_fifo.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/base/xpm_sync_fifo.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/mfpga_top.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/coe/hmc7044_cfg.coe"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/ddr3_mig/mig_a.prj"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/msg_comm/slave_comm_tx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/test_sim_fifo/test_sim_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/test_encode_fifo/test_encode_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/test_data_to_ddr3_fifo/test_data_to_ddr3_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/fbc_voltage_fifo/fbc_voltage_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/bpsi_fbc_fifo/bpsi_fbc_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/bps_divider/bps_divider.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/spi_slave_ack_fifo/spi_slave_ack_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/laser_rx_fifo/laser_rx_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/ddr3_mig/ddr3_mig.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/FBC_vout_buffer_fifo/FBC_vout_buffer_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/laser_uart_fifo/laser_uart_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/aurora_64b66b_1/aurora_64b66b_1.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/eds_to_aurora_fifo/eds_to_aurora_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/sync_eds_encode_fifo/sync_eds_encode_fifo.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/rx_dist_mem/rx_dist_mem.xci"]"\
 "[file normalize "$origin_dir/project_src/sources_1/ip/acc_demo_encode_mem/acc_demo_encode_mem.xci"]"\
 "[file normalize "$origin_dir/project_src/constrs_1/new/debug.xdc"]"\
 "[file normalize "$origin_dir/project_src/constrs_1/new/timing.xdc"]"\
 "[file normalize "$origin_dir/project_src/constrs_1/new/mfpga_io_v2.xdc"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/ddr_sim/wiredly.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/ddr_sim/ddr3_model.sv"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/ddr/tb_ddr_top.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/tb_acc_demo_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/tb_laser_aom_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/tb_FBC_cache.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/tb_acc_demo_flag_trim.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/tb_fast_shutter_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/overload/aom_trig_overload.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/testbench/message_comm_tx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/testbench/tb_encode_align.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/testbench/pcie_sim/pcie_aurora_64b66b_rx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/testbench/tb_bpsi_top_if_v2.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/testbench/tb_slave_comm.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/testbench/tb_encode_process.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/testbench/tb_laser_comm_ctrl.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/sim_acc_demo_flag_rx_drv.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/acc_demo_flag_tx_drv.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/msg_comm/message_comm_rx.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/spi/tb_spi_master.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/serial_slave_drv.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/serial/encode_rx_drv.v"]"\
 "[file normalize "$origin_dir/project_src/sources_1/new/spi/spi_reg_map.v"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find remote file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "project_1"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "project_1.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/project_1"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7k325tffg900-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip.user_files_dir" -value "D:/../work/project/FPGA/timing_mfpga_prj/${_xil_proj_name_}/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "D:/work/project/FPGA/timing_mfpga_prj/${_xil_proj_name_}/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "part" -value "xc7k325tffg900-2" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "D:/../work/project/FPGA/timing_mfpga_prj/${_xil_proj_name_}/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "sim.ipstatic.source_dir" -value "D:/../work/project/FPGA/timing_mfpga_prj/${_xil_proj_name_}/${_xil_proj_name_}.ip_user_files/ipstatic" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "278" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "279" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "279" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "279" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "278" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "279" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "279" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "1188" -objects $obj
set_property -name "xpm_libraries" -value "XPM_CDC XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/master_wr_fifo/master_wr_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/hmc7044_cfg_rom/hmc7044_cfg_rom.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/encode_align_fifo/encode_align_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/encode_x_align_fifo/encode_x_align_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/cache_rd_fifo/cache_rd_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/FBC_vin_buffer_fifo/FBC_vin_buffer_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/fbc_cache_fifo/fbc_cache_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/cache_bit_ram/cache_bit_ram.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/msg_comm_rx_ram/msg_comm_rx_ram.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/msg_comm_tx_fifo/msg_comm_tx_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/pll_2/pll_2.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/pll/pll.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/CRC32_D8.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/FBC_cache.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/FBC_vin_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/FBC_vout_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/motor/PID_control_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/acc_ctrl_rx_drv.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/acc_demo_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/acc_demo_flag_trim.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/acc_time_ctrl_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ad5445_config.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ad5592_config.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ad5592_spi_if.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ad7680_spi_if.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/align_unit.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/arbitrate_bpsi.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_clock_module.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/aurora_64b66b_0_exdes.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_gt_common_wrapper.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_support.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_0_support_reset_logic.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_clock_module.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/aurora_64b66b_1_exdes.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_support.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/shared_logic/aurora_64b66b_1_support_reset_logic.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/aurora_64b/aurora_64b66b_tx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/bpsi_top_if_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/motor/bspi_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/command_map.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/ddr_top.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds_frame_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds/eds_top_if.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/encode_align.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/encode_align_unit.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/encode_continuity_check.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/encode_process.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/encode_process_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/encode_tx_drv.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/fast_shutter_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/motor/fbc_sensor_process.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/fpga_heart_beat.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/base/handshake.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/hmc7044_config.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/hmc7044_spi_if.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds/image_rx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds/iser2des_1_to_12.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/laser_aom_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/laser_comm_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds/lval_synncode_0chan.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds/lval_synncode_Nchan.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/max5216_spi_if.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/mem_burst_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/mem_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/mem_read_arbi.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/mem_vin_buffer_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/mem_vout_buffer_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/mem_write_arbi.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/motion_top_if.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/pmt_master_sel.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/reg_delay.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/reset_generate.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/scan_cmd_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/scan_flag_generate.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/scan_state_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/serial_master_drv.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/serial_rx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/serial_rx_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/serial_tx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/serial_tx_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/msg_comm/slave_comm.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/msg_comm/slave_comm_rx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/msg_comm/slave_comm_x4_tx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds/train_word_align.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/eds/training.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/motor/trigger_generate.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/uart/uart.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/uart/uart_rx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/uart/uart_tx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/w_encoder_process_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/base/widen_enable.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/x_encoder_process.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/base/xpm_async_fifo.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/base/xpm_sync_fifo.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/mfpga_top.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/coe/hmc7044_cfg.coe"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/ddr3_mig/mig_a.prj"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/msg_comm/slave_comm_tx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/test_sim_fifo/test_sim_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/test_encode_fifo/test_encode_fifo.xci"] \
 [file normalize "${origin_dir}/project_src/sources_1/ip/test_data_to_ddr3_fifo/test_data_to_ddr3_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/master_wr_fifo/master_wr_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/hmc7044_cfg_rom/hmc7044_cfg_rom.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/encode_align_fifo/encode_align_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/encode_x_align_fifo/encode_x_align_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/cache_rd_fifo/cache_rd_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/FBC_vin_buffer_fifo/FBC_vin_buffer_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/fbc_cache_fifo/fbc_cache_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/cache_bit_ram/cache_bit_ram.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/msg_comm_rx_ram/msg_comm_rx_ram.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/msg_comm_tx_fifo/msg_comm_tx_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/pll_2/pll_2.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/pll/pll.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/ddr3_mig/mig_a.prj"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "scoped_to_cells" -value "ddr3_mig" -objects $file_obj

set file "$origin_dir/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/project_src/sources_1/ip/test_sim_fifo/test_sim_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/test_encode_fifo/test_encode_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}

set file "$origin_dir/project_src/sources_1/ip/test_data_to_ddr3_fifo/test_data_to_ddr3_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "mfpga_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/fbc_voltage_fifo/fbc_voltage_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/fbc_voltage_fifo/fbc_voltage_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/bpsi_fbc_fifo/bpsi_fbc_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/bpsi_fbc_fifo/bpsi_fbc_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/bps_divider/bps_divider.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/bps_divider/bps_divider.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/spi_slave_ack_fifo/spi_slave_ack_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/spi_slave_ack_fifo/spi_slave_ack_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/laser_rx_fifo/laser_rx_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/laser_rx_fifo/laser_rx_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/ddr3_mig/ddr3_mig.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/ddr3_mig/ddr3_mig.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/FBC_vout_buffer_fifo/FBC_vout_buffer_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/FBC_vout_buffer_fifo/FBC_vout_buffer_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/laser_uart_fifo/laser_uart_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/laser_uart_fifo/laser_uart_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/aurora_64b66b_1/aurora_64b66b_1.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/aurora_64b66b_1/aurora_64b66b_1.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/eds_to_aurora_fifo/eds_to_aurora_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/eds_to_aurora_fifo/eds_to_aurora_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/aurora_64b66b_0/aurora_64b66b_0.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/sync_eds_encode_fifo/sync_eds_encode_fifo.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/sync_eds_encode_fifo/sync_eds_encode_fifo.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/rx_dist_mem/rx_dist_mem.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/rx_dist_mem/rx_dist_mem.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/ip/acc_demo_encode_mem/acc_demo_encode_mem.xci"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sources_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/ip/acc_demo_encode_mem/acc_demo_encode_mem.xci"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "generate_files_for_reference" -value "0" -objects $file_obj
set_property -name "registered_with_manager" -value "1" -objects $file_obj
if { ![get_property "is_locked" $file_obj] } {
  set_property -name "synth_checkpoint_mode" -value "Singular" -objects $file_obj
}


# Set 'sources_1' fileset file properties for local files
# None

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/project_src/constrs_1/new/debug.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/project_src/constrs_1/new/debug.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/project_src/constrs_1/new/timing.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/project_src/constrs_1/new/timing.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Add/Import constrs file and set constrs file properties
set file "[file normalize "$origin_dir/project_src/constrs_1/new/mfpga_io_v2.xdc"]"
set file_added [add_files -norecurse -fileset $obj [list $file]]
set file "$origin_dir/project_src/constrs_1/new/mfpga_io_v2.xdc"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets constrs_1] [list "*$file"]]
set_property -name "file_type" -value "XDC" -objects $file_obj

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "target_constrs_file" -value "[file normalize "$origin_dir/project_src/constrs_1/new/debug.xdc"]" -objects $obj
set_property -name "target_part" -value "xc7k325tffg900-2" -objects $obj
set_property -name "target_ucf" -value "[file normalize "$origin_dir/project_src/constrs_1/new/debug.xdc"]" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/ddr_sim/wiredly.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/ddr_sim/ddr3_model.sv"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/ddr/tb_ddr_top.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/tb_acc_demo_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/tb_laser_aom_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/tb_FBC_cache.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/tb_acc_demo_flag_trim.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/tb_fast_shutter_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/overload/aom_trig_overload.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/testbench/message_comm_tx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/testbench/tb_encode_align.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/testbench/pcie_sim/pcie_aurora_64b66b_rx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/testbench/tb_bpsi_top_if_v2.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/testbench/tb_slave_comm.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/testbench/tb_encode_process.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/testbench/tb_laser_comm_ctrl.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/sim_acc_demo_flag_rx_drv.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/acc_demo_flag_tx_drv.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/msg_comm/message_comm_rx.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/spi/tb_spi_master.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/serial_slave_drv.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/serial/encode_rx_drv.v"] \
 [file normalize "${origin_dir}/project_src/sources_1/new/spi/spi_reg_map.v"] \
]
add_files -norecurse -fileset $obj $files

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/project_src/sources_1/new/ddr/ddr_sim/ddr3_model_parameters.vh"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "$origin_dir/project_src/sources_1/new/ddr/ddr_sim/ddr3_model.sv"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "SystemVerilog" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "tb_ddr_top" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "verilog_define" -value "SIMULATE" -objects $obj
set_property -name "xsim.simulate.add_positional" -value "1" -objects $obj
set_property -name "xsim.simulate.log_all_signals" -value "1" -objects $obj
set_property -name "xsim.simulate.no_quit" -value "1" -objects $obj
set_property -name "xsim.simulate.saif_all_signals" -value "1" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7k325tffg900-2 -flow {Vivado Synthesis 2021} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2021" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xc7k325tffg900-2" -objects $obj
set_property -name "auto_incremental_checkpoint.directory" -value "D:/work/project/FPGA_Project/timing_mfpga_prj/project_1/project_1.srcs/utils_1/imports/synth_1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7k325tffg900-2 -flow {Vivado Implementation 2021} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2021" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xc7k325tffg900-2" -objects $obj
set_property -name "auto_incremental_checkpoint.directory" -value "D:/test_project/work/project/FPGA_Project/timing_mfpga_prj/project_1/project_1.srcs/utils_1/imports/impl_1" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.bin_file" -value "1" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
